apiVersion: v1
kind: Service
metadata:  
  name: second-node-port
spec:
  selector:    
    app: my-app
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30037
    protocol: TCP
